### ISSUE TITLE
strong delay when opening h5/xml from network share (introduced in bigdataviewer-core-10.4.6) 

### ISSUE THREAD

**Issue by CellKai** [bigdataviewer/bigdataviewer-core#165] opened 2023-07-27 10:27 UTC
# issue description

- when opening h5/xml **from a network share**, display in BDV has a strong delay since bigdataviewer-core-10.4.6 and above.
- what used to take seconds with bigdataviewer-core-10.4.5 now takes 5 minutes or more.
- the delay only happens when the dataset is loaded **for the first time in a given Fiji session**
- storing files on a network share is our common use case. In our facility we provide our user with 60+ virtual machines that all use a common network storage.

# reproduce the issue
* download  T2_sect2_h5_tp0.zip (38.1 GB) 
https://filesender.switch.ch/filesender2/?s=download&token=06cdbadb-406f-4e52-aafc-11175bac322a
* store on a network location

_note: I truncated the dataset (original: 1 angle, 3 channels, 1 illumination, 100 tiles, 12 timepoints, ~400 GB, registered but not fused) and included only timepoint 0, the other partitions are missing on purpose so the upload is smaller (38 GB)._

* open in Fiji using ` Plugins › BigDataViewer › Open XML/HDF5` 
  * opening/displaying this truncated dataset with bigdataviewer-core-10.4.5 : ~10sec
  * with with bigdataviewer-core-10.4.6 and above: 5 min

## crosspost 
https://forum.image.sc/t/bigstitcher-n5-api-fused-n5-hdf5-has-no-pyramids-and-does-not-display-well-in-bdv/80925/21

## initial debugging by @NicoKiaru 
https://forum.image.sc/t/bigstitcher-n5-api-fused-n5-hdf5-has-no-pyramids-and-does-not-display-well-in-bdv/80925/16?u=cellkai

and following posts

## additional tests
loading a 400 GB 16 tile h5/xml from a network location using bigdataviewer-core-10.4.6 and above does not have such a strong delay. It seems hence that the delay correlates with the number of tiles.

**Comment by NicoKiaru** [comment] 2023-07-27 10:37
@CellKai maybe precise your OS ?

**Comment by tpietzsch** [comment] 2023-07-27 12:38
@NicoKiaru @CellKai thanks for debugging!!!

It looks like it could be really caused by the `H5Oget_info_by_name` call.
This was introduced between bigdataviewer-core-10.4.5 and bigdataviewer-core-10.4.6.

This is used here
https://github.com/bigdataviewer/bigdataviewer-core/blob/d43472e7c9afed4b0caec9794b6b12ec80b4a895/src/main/java/bdv/img/hdf5/HDF5Access.java#L154-L165
to check for the existence of a dataset.
I was expecting this to be better performance than just trying to open the dataset (LOL... Always a good idea to try to improve performance by guessing instead of measuring...)

Here is a thread about H5Oget_info_by_name performance problems: https://www.mail-archive.com/hdf-forum@hdfgroup.org/msg02058.html

So this should be replaced by just trying to opening and closing the dataset.
@NicoKiaru Would you try to see if it can be fixed this way? (Otherwise, I'll try to do it next week).

**Comment by CellKai** [comment] 2023-07-27 13:22
> @CellKai maybe precise your OS ?

certainly! I tested using Fiji-win64 on Windows 10.

**Comment by NicoKiaru** [comment] 2023-07-28 14:07
Not sure how to test it, but I commented the additional check...

```
			if ( dataSet == null ) //&& datasetExists( pathName ) )
```

... and then it's opening fast.

**Comment by mkitti** [comment] 2023-07-29 17:10
It would be better if we could use `H5Ovisit3` or `H5Literate2`.


https://docs.hdfgroup.org/hdf5/develop/group___h5_o.html#ga6d03115ae0e5e5b516bbf35bb492266a

https://docs.hdfgroup.org/hdf5/develop/group___t_r_a_v.html#gad7ca4206f06b5ada85b6ec5867ec6c73

**Comment by mkitti** [comment] 2023-07-29 17:18
Note that upstream version of `H5Oget_info_by_name` is now on version 3:

https://docs.hdfgroup.org/hdf5/develop/group___h5_o.html#gabb69c962999e027cef0079bbb1282199

**Comment by mkitti** [comment] 2023-07-31 19:47
Here is the stack trace

* [`ch.systemsx.cisd.hdf5.hdf5lib.HDFHelperH5Oget_info_by_name`](https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/ch/systemsx/cisd/hdf5/hdf5lib/HDFHelper.java#L78-105).
* [`hdf.hdf5lib.H5.H5Oget_info_by_name(long loc_id, String name, long lapl_id)`](https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/hdf/hdf5lib/H5.java#L4167-4170
)
* [`hdf.hdf5lib.H5.H5Oget_info_by_name(loc_id, name, HDF5Constants.H5O_INFO_ALL, lapl_id)`](https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/hdf/hdf5lib/H5.java#L4192-4193)
* [`Java_hdf_hdf5lib_H5_H5Oget_1info_1by_1name`](https://sissource.ethz.ch/sispub/jhdf5/-/blame/master/source/c/jni/h5oImp.c#L173-235)
* [`H5Oget_info_by_name2`](https://docs.hdfgroup.org/hdf5/v1_10/group___h5_o.html#title21)

The problem is that you have requested [`H5O_INFO_ALL`](https://docs.hdfgroup.org/hdf5/v1_10/group___h5_o.html#title21) while you just need [`H5O_INFO_BASIC`](https://docs.hdfgroup.org/hdf5/v1_10/group___h5_o.html#title21). 

The quickest fix is to use [hdf.hdf5lib.H5.H5Oget_info_by_name(loc_id, name, HDF5Constants.H5O_INFO_BASIC, lapl_id)](https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/hdf/hdf5lib/H5.java#L4192-4193)

https://docs.hdfgroup.org/hdf5/v1_14/classhdf_1_1hdf5lib_1_1_h_d_f5_constants.html#ae0c383b646260260d6f1626c21e738b9

**Comment by tpietzsch** [comment] 2023-08-03 08:39
Thanks a lot for the pointers @mkitti!
I pushed the fix to `master` https://github.com/bigdataviewer/bigdataviewer-core/commit/20a70342ef02f0997c6899029dac417bd88ff300

@NicoKiaru Could you try whether this solves the performance?

If it does, then I should apply the fix also for export, and in https://github.com/saalfeldlab/n5-hdf5.

**Comment by NicoKiaru** [comment] 2023-08-03 08:53
Yep, all good, it opens fast now.

**Comment by StephanPreibisch** [comment] 2023-08-03 15:01
Awesome :)

**Comment by tpietzsch** [comment] 2023-08-04 08:59
I released `bigdataviewer-core-10.4.9` with the fixes, and made a PR https://github.com/saalfeldlab/n5-hdf5/pull/31 to fix n5-hdf5

**Closed by tpietzsch** 2023-08-04 08:59 UTC

**Comment by Eddymorphling** [comment] 2024-10-14 15:48
Hi Al @tpietzsch @StephanPreibisch This issue seems to have resurfaced again. BigStitcher fusion now takes exceptionally longer than it used it. I am a regular fan of updating BigStitcher on Fiji, any recent changes that was implemented recently that  could trigger this?

**Comment by mkitti** [comment] 2024-10-15 06:42
@Eddymorphling I suggest creating a new issue with details about when you encounter this issue along with reproduction instructiona and versions of installed Fiji plugins.
